platform :ios, '13.0'
require_relative '../node_modules/react-native/scripts/react_native_pods'

project 'amazon-ivs-broadcast-react-native.xcodeproj'

target 'amazon-ivs-broadcast-react-native' do
  config = use_native_modules!

  use_react_native!(:path => config[:reactNativePath])

  # Amazon IVS Broadcast SDK (1.31.0)
  pod 'AmazonIVSBroadcast', '~> 1.31.0'
end 